apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-website-example
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - path: tools/helm/my-chart
      repoURL: https://github.com/dag-andersen/kubecon-us-2025-code.git
      targetRevision: main
      helm:
        valuesObject:
          replicaCount: 2
          serviceAccount:
            annotations:
              find: me