apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubecon-repo
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/dag-andersen/kubecon-us-2025-code
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-website-example
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: tools/helm/my-chart
      sourceRef:
        kind: GitRepository
        name: kubecon-repo
        namespace: flux-system
  targetNamespace: default
  values:
    replicaCount: 1
